export const ACTION_REQUEST = 'ACTION_REQUEST' // 发送异步请求的接口
export const ACTION_RECEIVE = 'ACTION_RECEIVE' // 接收异步返回的状态

export const ACTION_ADD_COMPONENT = 'ACTION_ADD_COMPONENT' // 添加组件
export const ACTION_DELETE_COMPEONT = 'ACTION_DELETE_COMPEONT' // 删除组件
export const ACTION_UPDATE_COMPEONT = 'ACTION_UPDATE_COMPEONT' // 更新组件
export const ACTION_UPDATE_GLOBAL_SETTING = 'ACTION_UPDATE_GLOBAL_SETTING' // 更新全局设置
export const ACTION_MOVEUP_COMPONENT = 'ACTION_MOVEUP_COMPONENT' // 组件上移
export const ACTION_MOVEDOWN_COMPONENT = 'ACTION_MOVEDOWN_COMPONENT' // 组件下移
